Update release-to-master-daily-sync.yml

diff --git a/.github/workflows/release-to-master-daily-sync.yml b/.github/workflows/release-to-master-daily-sync.yml
--- a/.github/workflows/release-to-master-daily-sync.yml
+++ b/.github/workflows/release-to-master-daily-sync.yml
@@ -32,7 +32,12 @@ jobs:
              
       - name: Checkout latest release branch
         run: |
-          git checkout -b ${{ env.LATEST_BRANCH }} origin/${{ env.LATEST_BRANCH }}
+          if git show-ref --verify --quiet refs/heads/${{ env.LATEST_BRANCH }}; then
+            git checkout ${{ env.LATEST_BRANCH }}
+          else
+            echo "Error: Branch ${{ env.LATEST_BRANCH }} does not exist."
+            exit 1
+          fi
         
       - name: Authenticate GitHub CLI
         run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
