Update release-to-master-daily-sync.yml

diff --git a/.github/workflows/release-to-master-daily-sync.yml b/.github/workflows/release-to-master-daily-sync.yml
--- a/.github/workflows/release-to-master-daily-sync.yml
+++ b/.github/workflows/release-to-master-daily-sync.yml
@@ -24,10 +24,11 @@ jobs:
           echo "LATEST_BRANCH=$LATEST_BRANCH" >> $GITHUB_ENV
           
       - name: Validate latest branch
-        run: if [ -z "${{ env.LATEST_BRANCH }}" ]; then
-               echo "Error: No release branch found."
-               exit 1
-             fi
+        run: |
+          if [ -z "${{ env.LATEST_BRANCH }}" ]; then
+            echo "Error: No release branch found."
+            exit 1
+          fi
              
       - name: Checkout latest release branch
         run: |
